# FOR AWS UBUNTU INSTANCE
FROM nikolaik/python-nodejs:python3.9-nodejs16

#RUN apt-get update && \
#	apt install -yqq python-dev && \
#	rm -rf /var/lib/apt/lists/*



#RUN pip install notebook
#
#RUN npm install -g ijavascript --loglevel verbose
#RUN ijsinstall --install=global

ENV PYTHONUNBUFFERED 1

# If we use --no-cache in docker build then it will run all the layers
# but we want only certain commands not to cache so we put this
# and build using $ docker build -t django_testing --build-arg CACHEBUST=$(date +%s_%N) .
ARG CACHEBUST=1

# create group id and then user (NOTE CHECK BEFORE THERE DOES NOT EXIST THE GROUP ID OR GROUP NAME)
RUN groupadd --gid 1000 simha \
  && useradd --uid 1000 --gid 1000 --create-home simha

ENV PIPENV_VENV_IN_PROJECT 1

WORKDIR /home/simha/app

# WORKDIR will create a folder with root privilages so change it to simha:users
# Note: when we do -v /host/folder:/home/simha/app then whatever the user:group
# /host/folder is there /home/simha/app will become that
# this is required only when are doing some files creation without bind mount
# but for clearity we will do chown
# ALSO chown for a root folder can be done by a root user only
RUN chown 1000:1000 /home/simha/app

USER simha

# Create docker image as below
# docker build -t python3.9-nodejs16-buster:nikolaik-python3.9-nodejs16 --file Dockerfile_node_python_buster .